project_name: guardian

builds:
  - main: ./main.go
    id: "guardian"
    binary: guardian
    flags:
      - -a
    ldflags:
      - -s -w -X github.com/odpf/guardian/main.Version={{.Tag}} -X github.com/odpf/guardian/main.BuildCommit={{.FullCommit}} -X github.com/odpf/guardian/main.BuildDate={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    env:
      - CGO_ENABLED=0
archives:
  - replacements:
      darwin: macos
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
release:
  draft: true
  prerelease: auto
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^build:'
dockers:
  -
    goos: linux
    goarch: amd64
    ids:
      - guardian
    dockerfile: Dockerfile
    image_templates:
      - 'docker.io/odpf/{{.ProjectName}}:latest'
      - 'docker.io/odpf/{{.ProjectName}}:{{ .Version }}'
      - 'docker.io/odpf/{{.ProjectName}}:{{ .Tag }}-amd64'
